{"name": "test_create_new_user_with_existing_data_return_error", "status": "passed", "description": "Вызываем метод /api/v1/courier и проверяем, что при повторе данных ручка отдает валидный ответ", "start": 1725791913133, "stop": 1725791914015, "uuid": "a90c890f-3efb-49b3-9f3a-b57ba0cd757b", "historyId": "8b699ca979ccf37b28df2eadc1d67f78", "testCaseId": "8b699ca979ccf37b28df2eadc1d67f78", "fullName": "tests.test_create_couriers.TestCreatingCourier#test_create_new_user_with_existing_data_return_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_couriers"}, {"name": "subSuite", "value": "TestCreatingCourier"}, {"name": "host", "value": "mchvell-book-m2-pro.local"}, {"name": "thread", "value": "80962-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_couriers"}]}